### ISSUE TITLE
AWS Functions return values not used.

### ISSUE THREAD

**Issue by Aljendro** [threadheap/serverless-ide-vscode#11]
VSCode: 1.32.3
Serverless IDE: 0.2.3

`!Join ['', ['cognito-idp.', !Ref Region, '.amazonaws.com/', !Ref UserPool]]`
returns a string but I get the error

`Incorrect type. Expected "string".`

Not sure how to configure the plugin so that it understands !Join returns a string.

**Comment by pavelvlasov** [comment]
thanks for reporting, @Aljendro 👍I'm working on a branch, that will allow using [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint) as a validator, so it will solve the problem. Will try to release it asap.

**Comment by Aljendro** [comment]
Thanks!

**Comment by pavelvlasov** [comment]
@Aljendro v0.3.1 is out and now [cfn-lint]() is used by default with a fallback to JSON schema. See [settings](https://github.com/threadheap/serverless-ide-vscode#settings) section for more info. Feel free to close the ticket if the problem goes away.

**Comment by Aljendro** [comment]
After installing cfn-lint, restarting system, trying to configure vscode, I am still getting the same result. Is there any extra configuration I need to do? I have run cfn-lint on the command line and it doesn't throw any errors on my cfn file... I've also provided the full path to cfn-lint, which doesn't help

**Comment by pavelvlasov** [comment]
@Aljendro issue is resolved in the latest version, feel free to reopen if the problem still persist
