### ISSUE TITLE
[serverless framework] httpApi does not support method: '*'

### ISSUE THREAD

**Issue by bdo** [threadheap/serverless-ide-vscode#110]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

This tool incorrectly classifies '*' as an invalid value for the httpApi method property.

* **The steps to reproduce**

Using this following fragment in serverless.yml:
```yml
functions:
  api:
    handler: myhandler
    events:
      - httpApi:
          method: '*'
          path: /
```

The plugin highlights '*' as invalid and displays the following error:
![image](https://user-images.githubusercontent.com/683020/99585213-5332ff00-29e6-11eb-83cc-61358df3ce66.png)

* **What is the expected behavior?**

No error highlighting as '*' is a valid value for the httpApi method.

* **What is the motivation / use case for changing the behavior?**

Using `any` as recommended by the plugin does not work and will lead to the following serverless validation error:
```
Serverless: Configuration warning at 'functions.api.events[0].httpApi.method': value 'any' does not satisfy pattern /^(?:\*|GET|POST|PUT|PATCH|OPTIONS|HEAD|DELETE)$/i
```

This means the only valid values for the serverless framework httpApi method are (case insensitive):
- *
- GET
- POST
- PUT
- PATCH
- OPTIONS
- HEAD
- DELETE

* **Please tell us about your environment:**
  
  - Plugin version: v0.5.26
  - VSCode version: 1.51.1
  - Template type: Serverless Framework

**Comment by pavelvlasov** [comment]
Thanks for reporting @bdo! The fix is effective in the latest version of the plugin.

**Comment by bdo** [comment]
Hi @pavelvlasov,

Thanks for replying so quickly to my issue !

However I tried again with version 0.5.26 and it's still not fixed.

By looking at your commit, I believe your fix applies to `http` not `httpApi`.

Please re-open including my related PR which fixes the httpApi schema.

**Comment by pavelvlasov** [comment]
thanks for pointing this out @bdo 👍 I updated httpAri definitions as well in the latest version.
