### ISSUE TITLE
Allow multiple file extensions in serverlessIDE.CloudFormation.templatePattern

### ISSUE THREAD

**Issue by mike-mosher** [threadheap/serverless-ide-vscode#12]
It would be great to have this extension apply to multiple file types.  CloudFormation templates are very commonly saved as: *.json, *.yaml, *.yml, *.cf.yaml, *.template, etc

It would be great to have the `serverlessIDE.CloudFormation.templatePattern` parameter allow multiple values, similar to the following:

```
"serverlessIDE.CloudFormation.templatePattern": "*.yml|*.yaml|*.json",
```

**Comment by pavelvlasov** [comment]
Thanks for reporting @mike-mosher 👍In the next release, I wanted to auto-detect cloud formation templates based on the file content. Would that work for your case or you want more granular config?

**Comment by mike-mosher** [comment]
Perfect, I like that even better.  

Only one thought:  The ability to still differentiate between CloudFormation templates and SAM templates.  If I set both `serverlessIDE.CloudFormation.templatePattern` and `serverlessIDE.SAM.templatePattern` to the same value (like `*.yaml`), then my CloudFormation templates always have the following error:  `Missing property "Transform"`.  

If you were able to successfully differentiate between CFN template and SAM template based on file contents, that would be the best ...

Thanks for the quick reply!
