### ISSUE TITLE
provided-al2 not unable in runtime

### ISSUE THREAD

**Issue by cedric-r-mycelium** [threadheap/serverless-ide-vscode#127]
Since last year amazon provide a new runtime as name `provided.al2` but it not enabled on `runtime `possible value

Can you add this ?

**Comment by PatMyron** [comment]
looks like one of these files:
https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/language-server/src/language-service/services/completion/constants.ts
https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/serverless-framework-schema/json/aws/common/runtime.json
