### ISSUE TITLE
"package.patterns" is not recognised

### ISSUE THREAD

**Issue by mileswatson** [threadheap/serverless-ide-vscode#139]
### Issue
"[Serverless IDE] Unexpected property patterns" is shown when using the patterns feature to exclude files from the package.

### Example 

```
package:
  patterns:
    - "!build/tests-unit/**"
```
### Expected behaviour
No error should be shown - "package.patterns" should be recognized as an array of strings.
https://www.serverless.com/framework/docs/providers/aws/guide/packaging#patterns

Sorry if this isn't the right place to report, I was confused by the note at the top of the template.

**Comment by ZackMitkin** [comment]
When will this patch be released? Kinda annoying having the error there :/

**Comment by phugodness** [comment]
same here, i have to disable it for a while :(
