### ISSUE TITLE
missing more http.integration types 

### ISSUE THREAD

**Issue by oreporan** [threadheap/serverless-ide-vscode#149]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
IDE error on `http.integrations: mock` while this is allowed [according to the docs](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#mock-integration)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.

![image](https://user-images.githubusercontent.com/2146999/149131931-8402d9cf-6c2d-40ab-aba4-7a30c5bcd181.png)

* **What is the expected behavior?**
allow "mock" as part of integrations

* **What is the motivation / use case for changing the behavior?**
Add to enum here - https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/serverless-framework-schema/json/aws/functions/events/http.json#L17

* **Please tell us about your environment:**
  
  - Plugin version: `v0.5.32`
  - VSCode version
  - Template type: `serverless.yml`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pavelvlasov** [comment]
Fixed in the latest release
