### ISSUE TITLE
adding dotnet6 as supported runtime type

### ISSUE THREAD

**Issue by LagerstedtMarcus** [threadheap/serverless-ide-vscode#171]
* **I'm submitting a ...**
  - [ ] bug report
  - [ x ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Adding new type of runtimes

* **What is the current behavior?**
dotnet6 ins not supported as a valid type but can be use since the launch of .net 6

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.

* **What is the expected behavior?**
That i can put dotnet6 as the functions runtime and not get the red underline on the text

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Plugin version
  - VSCode version THIS IS WHAT I USED
  - Template type

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pavelvlasov** [comment]
Support will be added in the latest release
