### ISSUE TITLE
False schema validation errors within Resources section in serverless.yml

### ISSUE THREAD

**Issue by orshemtov** [threadheap/serverless-ide-vscode#172]
**Note: what to raise a request for unknown/new or required field or resource, then raise a PR**.
#68 and #62
are good examples of updating a schema definition. It should not take longer that 15 minutes.

**What to prioritizer bugfix or feature?**
Hit that ❤️support button on the top of the screen.

**And don't forget to 🌟star the repo**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

report a bug

* **What is the current behavior?**

Im using VSCode and the Serverless IDE extension, and the JSON schema "Serverless Framework Configuration"

This is the schema:
https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json

![image](https://user-images.githubusercontent.com/64565195/197879974-198c436a-0ae3-4ab5-9c5c-5ce4b1169c43.png)

For some reason, almost all AWS resources show an error in schema validation when defined under `resources.Resources` section, like so:

![image](https://user-images.githubusercontent.com/64565195/197880071-6bbe041c-379d-4b8a-9521-
58db0e17e396.png)

For some odd reason, it expects every resource I put in to be of type `AWS::AmazonMQ::Broker`:

![image](https://user-images.githubusercontent.com/64565195/197880247-41459871-590b-4dca-b565-c11e4030607d.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar.

* **What is the expected behavior?**

No validation errors, correct auto-completion for resources parameters

* **What is the motivation / use case for changing the behavior?**

It confuses the user, saying there's an error when there's not, it causes static checkers and IDE to show up "red" in places that do not require attention

* **Please tell us about your environment:**
  
  - Plugin version `0.5.34`
  - VSCode version `1.72.2`
  - Template type 

JSON schema - `https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by martindanielsson** [comment]
I ran into the same issue and it went away when I uninstalled the YAML extension, not sure if there's a way to get these two to work at the same time 🤔

**Comment by pavelvlasov** [comment]
Should be resolve in the latest release
