### ISSUE TITLE
Incorrect error when moving runtime from provider to separate function file

### ISSUE THREAD

**Issue by andreimcristof** [threadheap/serverless-ide-vscode#34]
Hi, 

This is regarding the "runtime" property in "provider". 

When I use a separate functions.yml file, like this: 
`functions: ${file(./functions/functions.yml)}
`

 and have different runtimes for each function, then I must move the "runtime" property away from the global "provider" setting and  into the functions.yml file under each function. At that point the extension incorrectly reports that the "runtime" property is missing in "provider".  Can it not detect that it was already moved to the functions.yml file? 
Thanks,

**Comment by pavelvlasov** [comment]
Hi @andreimcristof, thanks for reporting 👍 

Yes, `runtime` property is marked as required in the schema.
Short term, it can be just removed from https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/serverless-framework-schema/json/aws/provider/provider.json#L297

But would be cool to have the same handling that was done for SAM globals, where defined required arguments are excluded from the checks.
