### ISSUE TITLE
Unnecessary reopening of output terminal on non serverless/cfn yaml files

### ISSUE THREAD

**Issue by Nadock** [threadheap/serverless-ide-vscode#39]
When I'm editing a `yml` file that is not a Serverless or CFN file, if I hover any symbol name in the file an output panel opens in VSCode and prints the following message:

```
[Error - 1:19:18 PM] Request textDocument/hover failed.
  Message: Document is not supported
  Code: 1 
```

This ends up happening every few seconds when I'm working on a file. Is there an option to disable the automatic opening of the output panel or an option to turn off things like the hover documentation on a per-file level?

**Comment by pavelvlasov** [comment]
thanks for reporting @Nadock 👍 You can disable hover in the settings for now, see https://github.com/threadheap/serverless-ide-vscode#settings

I'll look into the issue later today and will try to have a fix

**Comment by Nadock** [comment]
Appreciate the quick response @pavelvlasov! This plugin is great btw, keep up the good work.
