### ISSUE TITLE
Approach for adding support for serverless-framework plugins?

### ISSUE THREAD

**Issue by maplesteve** [threadheap/serverless-ide-vscode#43]
Congrats for a very useful tool!

What would be the best approach to add support for the various plugins available for the serverless-framework?

From the directory structure, I would assume, that they should go into a new directory `serverless-ide-vscode/packages/serverless-framework-schema/json/plugins/`
with a dedicated directory for each plugin where the necessary JSON files could live.

E.g. for the serverless-step-functions plugin, the `$ref` property in `stepfunctions.json` would point to `"$ref": "#/definitions/stepfunctions:stateMachines:stateMachine"` and a second JSON file `stateMachine` would define the properties the plugin expects.

**Comment by pavelvlasov** [comment]
hey @maplesteve 👋

The approach sounds good to me 👍

It will require some extra work if the plugin is expected to be in the `plugins` list. There is a concept of mutations, that applies changes to the schema based on the file contents (https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/language-server/src/language-service/services/jsonSchema/mutation/index.ts), but it's probably not required as for now.

**Comment by pavelvlasov** [comment]
v0.4.11 allows for some additional properties on, so at least plugin won't show errors for most of the plugins.

**Comment by pavelvlasov** [comment]
@maplesteve would be great if you could contribute and add support for step functions
