### ISSUE TITLE
Doesn't take globals into account

### ISSUE THREAD

**Issue by tj** [threadheap/serverless-ide-vscode#5]
This is sweet! 

Maybe on your list already but I noticed it doesn't take globals into account for function properties etc, and thinks you're missing a few required props such as `Runtime` for a function.

**Comment by pavelvlasov** [comment]
thanks for reporting @tj! It's definitely something I want to look next.

That's a similar problem with autocompletion/validation of resources references, so I need to spend some time to reason about and maybe I can build a basis for both.

**Comment by pavelvlasov** [comment]
Resolved in [v0.2.1](https://github.com/threadheap/serverless-ide-vscode/releases/tag/v0.2.1)

**Comment by tj** [comment]
awesome!
