### ISSUE TITLE
Missing property "input" for schedule event

### ISSUE THREAD

**Issue by carlin-q-scott** [threadheap/serverless-ide-vscode#52]
I'm getting the following lint error for my schedule event:
> Missing property "input"

This property is not required, at least [not for AWS](https://serverless.com/framework/docs/providers/aws/events/schedule/).

**Comment by pavelvlasov** [comment]
Thanks for reporting @carlin-q-scott 👍 The issue is fixed in the latest version of the plugin.

**Comment by carlin-q-scott** [comment]
Wow, that's the fastest response I've ever gotten from a FOSS project. Thanks!
