### ISSUE TITLE
Value not accepted for nodejs12.x Runtime

### ISSUE THREAD

**Issue by Zurnaz** [threadheap/serverless-ide-vscode#55]
Runtime support was added for nodejs12.x but an linting error appear when using the nodejs12.x as a runtime.

Is it just a case of adding the value to these files?

packages/serverless-framework-schema/json/aws/common/runtime.json
packages/language-server/src/language-service/services/completion/constants.ts

**Comment by pavelvlasov** [comment]
Thanks for reporting @Zurnaz 👍 

Correct, you will need to make changes to these files and generate a new schema.

**Comment by pavelvlasov** [comment]
Resolved in v0.5.6
