### ISSUE TITLE
'>Helpers: Install cfn-lint' tried to use brew on Windows

### ISSUE THREAD

**Issue by carlin-q-scott** [threadheap/serverless-ide-vscode#56]
The helper for installing the linter tried to use the `brew` command to install the linter. It should have used `py -m pip install cfn-lint`. Perhaps this happened because I don't have pip installed globally.

**Comment by pavelvlasov** [comment]
hey, @carlin-q-scott 👋 thanks for reporting. I guess the check here https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/vscode/src/validation-error-dialog/index.ts#L83 is broken. I, unfortunately, don't have a windows machine to test it.

Can you have a look at that by any chance?

**Comment by carlin-q-scott** [comment]
Thanks for pointing to that. I actually ran the command using the command pallet (ctrl+shift+p). I believe this line registers the helper: https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/vscode/src/commands/index.ts#L7.

The dialog is correctly loading the link.

I'm working on support linux/windows since they should both use pip to install the command.

**Comment by pavelvlasov** [comment]
I see. I guess the check should be performed in two places then. The first one to show button for supported platforms and the second one https://github.com/threadheap/serverless-ide-vscode/blob/master/packages/vscode/src/commands/index.ts#L7 to run the proper command.

**Comment by carlin-q-scott** [comment]
Yep, this is what my changes are looking like: https://github.com/carlin-q-scott/serverless-ide-vscode/blob/patch-1/packages/vscode/src/commands/index.ts#L8-L28

**Comment by pavelvlasov** [comment]
@carlin-q-scott the fix is out in the latest version. Feel free to reopen an issue is something goes wrong
