### ISSUE TITLE
How to enable hover tooltip when separate configuration to its own YAML file

### ISSUE THREAD

**Issue by Albert-Gao** [threadheap/serverless-ide-vscode#65]
Hi, thanks for this fantastic extension!

Just one quick question:

When I adding configuration in `serverless.yml`, I can see the onHover tooltip:
![image](https://user-images.githubusercontent.com/18282328/72596810-74027200-3947-11ea-8f2e-2e0d4c7fd73f.png)

But If I separate the configuration to its own file:

```yaml
resources:
  - ${file(awsResources/TcUserPool.yml)}
```

Then in the `TcUserPool.yml`, no tooltip when hover:

![image](https://user-images.githubusercontent.com/18282328/72596907-a14f2000-3947-11ea-957c-513ed9e79f01.png)

The linting is there though:
![image](https://user-images.githubusercontent.com/18282328/72597006-d491af00-3947-11ea-93ff-613a1e260666.png)

If I install `vscode-cfn-lint`, then I can see the onHover tooltop with a URL rather than text:
![image](https://user-images.githubusercontent.com/18282328/72597085-fd19a900-3947-11ea-9fb5-6fb5f3dbb4fc.png)

Anything I am missing :) thanks

**Comment by pavelvlasov** [comment]
hey, @Albert-Gao could try to reopen vscode? Tooltips should be back.
I suspect there are some problems with registering schema for the nested imports.

**Comment by coyoteecd** [comment]
Can confirm it's working, I am using the same setup with CloudFormation resources in their own files, and tooltips work fine.

**Comment by pavelvlasov** [comment]
@Albert-Gao  I'm closing the issue for now. Feel free to reopen if you have more info on how to reproduce it.

**Comment by witwit** [comment]
Hover does not work in separate resource files (YML), using the version deployed on:
7/17/2022, 07:17:31
