### ISSUE TITLE
Support for some short-form AWS Functions

### ISSUE THREAD

**Issue by Jesavino** [threadheap/serverless-ide-vscode#75]
Currently, I'm seeing behavior where `!If` and `!Equals` don't appear to be supported. 

An example:
![image](https://user-images.githubusercontent.com/6265979/74837891-78c49800-52f0-11ea-92b1-bf3119312970.png)

The syntax error on the `!If` line shows `[Serverless IDE] Incorrect type. Expected "string".`. This can be fixed by substituting `Fn::If` instead of the shorthand. 

The syntax error on the `!Equals` line simply reports `[Serverless IDE] Incorrect type. Expected "object".`, which I think is just a bug since the existing type should be fine.

**Comment by ruchevits** [comment]
+1 Would be amazing!

**Comment by pavelvlasov** [comment]
@Jesavino @ruchevits the issue should be gone in the latest version of the plugin. Feel free to reopen if there are some other problems with short forms.
