### ISSUE TITLE
CloudFormation template stops autocompleting if included in Serverless

### ISSUE THREAD

**Issue by theoribeiro** [threadheap/serverless-ide-vscode#76]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
If you have a serverless.yml file that includes a Cloudformation Template in another file say:
```
service: sample-service
provider: 
    name: aws
...
resources:
    - ${file(sample.yml)}
```

Sample.yml stops autocompleting. As soon as I comment the line that includes the file in the resources section, the file starts autocompleting again.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1) Create a serverless project
2) Create a CloudFormation template file with a sample resource. Check autocomplete works.
3) Include file in serverless.yml `resources` section
4) Check that CloudFormation file no longer autocompletes

* **What is the expected behavior?**
CloudFormation template file autocompletes regardless of being included

* **What is the motivation / use case for changing the behavior?**
Better productivity

* **Please tell us about your environment:**
  
  - Plugin version: 0.5.16
  - VSCode version: 1.43.0
  - Template type: Serverless and CloudFormation

**Comment by pavelvlasov** [comment]
The issue should be resolved in the latest version of the plugin.
