### ISSUE TITLE
Serverless variable use causes an E1029 error.

### ISSUE THREAD

**Issue by grant116** [threadheap/serverless-ide-vscode#77]
I am using Serverless IDE 0.5.16 and VSCode version 1.43.1. I am creating some SQS queues in a yml file.   When using a Serverless variable it is marked with an E1029 error. 
`
  LoggerQueue:
      Type: AWS::SQS::Queue
      Properties:
          QueueName: ${self:custom.queues.loggerQueue}
`

> [Serverless IDE] E1029: Found an embedded parameter outside of an "Fn::Sub" at Resources/LoggerQueue/Properties/QueueName

 If I change the variable to a literal it does not complain.  

`
  LoggerQueue:
      Type: AWS::SQS::Queue
      Properties:
          QueueName: 'ABC'
`

I would assume this should not be marking this as an issue since the plugin supports the Serverless framework.

**Comment by pavelvlasov** [comment]
@grant116 could you try to wrap the string with `"${self:custom.queues.loggerQueue}"`. I think the error should go away

**Comment by grant116** [comment]
Hello @pavelvlasov I tried wrapping the string with a double quote and the error did not go away. Thank you.

**Comment by pavelvlasov** [comment]
The issue with imports should be resolved in the latest version of the plugin.
