### ISSUE TITLE
[feature-request] Ability to ignore linting in specific parts

### ISSUE THREAD

**Issue by ircmgr** [threadheap/serverless-ide-vscode#83]
I am using file stitching in my yml config ( serverless framework ) so because of that sometimes the logical names of some instances do not exist in the same file until stitching on deploy.
this will correctly trigger an  error of (example) "E1010: Invalid GetAtt ElasticSearchInstance.DomainEndpoint for resource AppsyncElasticDataSource"

example :
serverless.yml

`
.....
.....
resources:
  - Resources:
  - ${file(./serviceConfig/appSync/appSyncResources.yml)}
  - ${file(./serviceConfig/elasticSearch/elasticResources.yml)}
.... 
...

`

appSyncResources.yml
`
 AppsyncElasticDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:  
        'Fn::GetAtt': [AppsyncGraphQlApi ,ApiId]
      Name: "elasticDTsource"
      Type: AMAZON_ELASTICSEARCH
      ElasticsearchConfig:
         AwsRegion: us-east-1
         Endpoint: 
########## 
FEATURE:    logical name ElasticSearchInstance exists in different file in this example in ./serviceConfig/elasticSearch/elasticResources.yml so it correctly errors 
so maybe something like #Ignore before would stop ide from erroring?
#########
          #Ignore => should ignore this err 
          Fn::Join: ['',['https://', Fn::GetAtt: [ElasticSearchInstance,DomainEndpoint] => 
         ]] 
      ServiceRoleArn: 
     .....
     ......

`

**Comment by pavelvlasov** [comment]
Problems with the imports should be resolved in the latest version of the plugin.
