### ISSUE TITLE
Validation error for valid template/configuration

### ISSUE THREAD

**Issue by ben-elsen** [threadheap/serverless-ide-vscode#86]
* **I'm submitting a bug report**

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug

* **What is the current behavior?**
The Serverless IDE plugin in VSCode gives the following error: 
[Serverless IDE] E0001: Error transforming template: Resource with id [UpdateCardconfigurationInDBFunction] is invalid. Event with id [EBRule] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: EventBridgeRule.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
I share the sam template via: https://plnkr.co/edit/IOn5bxpBrGZWG42O

* **What is the expected behavior?**
I would not expect an error as everything is like it should according to the SAM doc (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html#sam-property-function-eventbridgerule--examples) and everything deploys beautifull.

* **What is the motivation / use case for changing the behavior?**
Have the validation correct.

* **Please tell us about your environment:**
  
  - Plugin version: v0.5.21
  - VSCode version: 1.46.0-insider
  - Template type: SAM

**Comment by pavelvlasov** [comment]
thanks for reporting @ben-elsen!
This error is coming from https://github.com/aws-cloudformation/cfn-python-lint, so you likely will need to update the package or raise an issue there.

**Comment by ben-elsen** [comment]
Thanks @pavelvlasov !
