### ISSUE TITLE
support serverless framework parameter

### ISSUE THREAD

**Issue by iam-yan** [threadheap/serverless-ide-vscode#92]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

Hi thanks for creating this extension. I'm using serverless framework so I'm wondering if it could support  parameters usage or there were some work around to avoid displaying relevant errors already?

Thanks

**Comment by pavelvlasov** [comment]
hey @juuyan! Could you provide an example of the config and an error?
